---
title: "population_productivity_analysis"
author: "Olivia Somhegyi"
date: "2023-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(kableExtra)
library(janitor)
```

```{r}
### data wrangling

## import data
coho <- readxl::read_xlsx(here('data', 'OC Coho Abundance.xlsx')) %>%
  clean_names() %>% 
  distinct()

## convert to a tibble
coho_ts <- coho %>%
 as_tibble(key = NULL, index = year) 

## calculate annual salmon return for each population. To do so, run a for loop to pass each population in the dataframe through the function
calculate_returns <- function(data) {
  rt <- numeric(length(data) - 1)  
  for (i in 2:length(data)) {
    rt[i-1] <- (data[i-1] / data[i]) - 1
  }
  return(rt)
} ## ‘i’ is the initial population from the previous year. ‘I-1’ is the current population for a given year we are looking at

## create new dataframe of calculated return data
returns <- data.frame(apply(coho[2:22], 2, calculate_returns))


### statistics of return data

## mean of each population return
rt_mean <- sapply(returns, mean)
rt_mean_df <- as.data.frame(rt_mean)

## mean of the metapopulation (esu) return
mean_all_rt <- mean(rt_mean)

## variance of each population return
rt_var <- sapply(returns, var)

## mean of variance of the metapopulation (esu) return
mean_var <- mean(rt_var)

## standard deviation of each population return
rt_sd <- sapply(returns, sd)

### create statistics table

## combine into one dataframe to make a table of the statistics
return_df <- data.frame(rt_mean, rt_var, rt_sd)

return_table <- return_df %>% 
  kable(col.names = c("Returns Mean", "Returns Variance", "Returns SD")) %>% 
  kable_styling(bootstrap_options = "striped",
                position = "left", full_width = FALSE)

## plot table
return_table
```

